"""add definition_path and profiler_path to model_version

Revision ID: 3ab229c897ea
Revises: 
Create Date: 2026-01-05 05:08:38.110476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ab229c897ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('dataset_perf')
    # op.drop_table('device_manage')
    # op.drop_table('device_metrics')
    # with op.batch_alter_table('device_types', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('name'))
    #
    # op.drop_table('device_types')
    # op.drop_table('device_perf')
    # with op.batch_alter_table('model_lib', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('name'))
    #
    # op.drop_table('model_lib')
    # with op.batch_alter_table('devices', schema=None) as batch_op:
    #     batch_op.alter_column('port',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True,
    #            existing_server_default=sa.text("'22'"))
    #     batch_op.alter_column('status',
    #            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
    #            nullable=True,
    #            existing_server_default=sa.text("'offline'"))
    #     batch_op.alter_column('removed',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('profiler_path', sa.String(length=512), nullable=True))

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_users_email'))
    #     batch_op.drop_index(batch_op.f('idx_users_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_column('profiler_path')
        batch_op.drop_column('definition_path')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('removed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False,
               existing_server_default=sa.text("'offline'"))
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'22'"))

    op.create_table('model_lib',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_lib', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('device_perf',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('flops', mysql.FLOAT(), nullable=True),
    sa.Column('avg_latency_ms', mysql.FLOAT(), nullable=True),
    sa.Column('compressed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_perf.id'], name=op.f('device_perf_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('device_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('device_metrics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature', mysql.FLOAT(), nullable=True),
    sa.Column('mem_usage', mysql.FLOAT(), nullable=True),
    sa.Column('cpu_usage', mysql.FLOAT(), nullable=True),
    sa.Column('gpu_usage', mysql.FLOAT(), nullable=True),
    sa.Column('ts', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_metrics_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('device_manage',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deviceType', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('temperature', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memoryUsed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpuUtil', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gpuUtil', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('online', 'offline', 'maintenance'), nullable=False),
    sa.Column('systemInfo', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dataset_perf',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('accuracy', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_lib.id'], name=op.f('dataset_perf_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
